In [8]:
from datasets import load_dataset

c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
dataset2 = load_dataset("batuhanmtl/job-skill-set")

In [10]:
df2 = dataset2["train"].to_pandas()

In [11]:
df2

,job_id,category,job_title,job_description,job_skill_set
0,3902668440,HR,Sr Human Resource Generalist,SUMMARY\nTHE SR. HR GENERALIST PROVIDES HR EXP...,"['employee relations', 'talent acquisition', '..."
1,3905823748,HR,Human Resources Manager,BE PART OF A STELLAR TEAM AT YSB AS THE MANAGE...,"['Talent Acquisition', 'Employee Performance M..."
2,3905854799,HR,Director of Human Resources,OUR CLIENT IS A THRIVING ORGANIZATION OFFERING...,"['Human Resources Management', 'Recruitment', ..."
3,3905834061,HR,Chief Human Resources Officer,JOB TITLE: CHIEF HUMAN RESOURCES OFFICER (CHRO...,"['talent management', 'organizational developm..."
4,3906250451,HR,Human Resources Generalist (Hybrid Role),DESCRIPTION\n\n WHO WE ARE \n\nAVI-SPL IS A DI...,"['Microsoft Office', 'Data analysis', 'Employe..."
...,...,...,...,...,...
1162,3905299905,BUSINESS-DEVELOPMENT,Intern - Business Development,REQUIREMENTS\n\n DESCRIPTION & REQUIREMENTS \n...,"['MS Office Suite', 'PowerPoint', 'Excel', 're..."
1163,3885829894,BUSINESS-DEVELOPMENT,Business Development Representative,IT'S FUN TO WORK IN A COMPANY WHERE PEOPLE TRU...,"['Collaboration', 'Communication', 'Problem So..."
1164,3901649881,BUSINESS-DEVELOPMENT,Enterprise Business Development Representative...,JOIN OUR DYNAMIC AI TEAM AS AN ENTERPRISE BUSI...,"['Salesforce', 'data analysis', 'lead generati..."
1165,3904049863,BUSINESS-DEVELOPMENT,Senior Director Business Development,ROOM 8 GROUP IS THE WORLD’S FASTEST GROWING ST...,"['business development', 'sales', 'corporate s..."
1166,3904084138,BUSINESS-DEVELOPMENT,Global Business Development Partner - 100% Remote,EXCITING OPPORTUNITY: GLOBAL BUSINESS DEVELOPM...,"['strategic marketing', 'business development'..."

In [12]:
import pandas as pd
df3 = pd.read_csv(r"C:\Users\Arun\Downloads\candidate_job_role_dataset.csv")

In [13]:
df3

,candidate_id,skills,qualification,experience_level,job_role
0,1,"Python, SQL, TensorFlow, Machine Learning, Com...",Master's in Data Science,Senior,Data Scientist
1,2,"HTML, CSS, JavaScript, React, Teamwork",Bachelor's in Computer Science,Mid,Frontend Developer
2,3,"Java, Spring, SQL, REST APIs, Problem Solving",Bachelor's in Software Engineering,Senior,Backend Developer
3,4,"Figma, Adobe XD, UI/UX Design, Creativity",Bachelor's in Design,Entry,Designer
4,5,"Python, Django, JavaScript, React, Agile",Master's in Computer Science,Mid,Full Stack Python Developer
...,...,...,...,...,...
995,996,"HR Management, Recruitment, Employee Relations",Master's in Human Resources,Senior,HR
996,997,"C#, .NET Core, Azure, SQL Server",Bachelor's in Computer Science,Mid,C# Developer
997,998,"Swift, iOS, Xcode, UI/UX",Bachelor's in Computer Science,Entry,Mobile Developer
998,999,"Network Security, Ethical Hacking, SIEM",Master's in Cybersecurity,Senior,Cybersecurity Engineer
999,1000,"Agile, JIRA, Stakeholder Management",Master's in Business Administration,Mid,Software Project Manager

In [14]:
df2.drop(columns=["job_id","category","job_description"],inplace= True)

In [15]:
import ast

def removing(df):
    df["job_skill_set"] = df["job_skill_set"].apply(
        lambda x: ", ".join(ast.literal_eval(x)) if isinstance(x, str) else ", ".join(x)
    )
    return df

df2 = removing(df2)

In [16]:
df2

,job_title,job_skill_set
0,Sr Human Resource Generalist,"employee relations, talent acquisition, perfor..."
1,Human Resources Manager,"Talent Acquisition, Employee Performance Manag..."
2,Director of Human Resources,"Human Resources Management, Recruitment, Emplo..."
3,Chief Human Resources Officer,"talent management, organizational development,..."
4,Human Resources Generalist (Hybrid Role),"Microsoft Office, Data analysis, Employee onbo..."
...,...,...
1162,Intern - Business Development,"MS Office Suite, PowerPoint, Excel, reporting,..."
1163,Business Development Representative,"Collaboration, Communication, Problem Solving,..."
1164,Enterprise Business Development Representative...,"Salesforce, data analysis, lead generation, co..."
1165,Senior Director Business Development,"business development, sales, corporate strateg..."
1166,Global Business Development Partner - 100% Remote,"strategic marketing, business development, tea..."

In [17]:
df3.drop(columns=["candidate_id","qualification","experience_level"],inplace= True)
df3

,skills,job_role
0,"Python, SQL, TensorFlow, Machine Learning, Com...",Data Scientist
1,"HTML, CSS, JavaScript, React, Teamwork",Frontend Developer
2,"Java, Spring, SQL, REST APIs, Problem Solving",Backend Developer
3,"Figma, Adobe XD, UI/UX Design, Creativity",Designer
4,"Python, Django, JavaScript, React, Agile",Full Stack Python Developer
...,...,...
995,"HR Management, Recruitment, Employee Relations",HR
996,"C#, .NET Core, Azure, SQL Server",C# Developer
997,"Swift, iOS, Xcode, UI/UX",Mobile Developer
998,"Network Security, Ethical Hacking, SIEM",Cybersecurity Engineer
999,"Agile, JIRA, Stakeholder Management",Software Project Manager

In [18]:
skills = pd.concat((df3["skills"],df2["job_skill_set"]),ignore_index=True)
title = pd.concat((df3["job_role"],df2["job_title"]),ignore_index=True)

In [19]:
df = {"skills":skills,
      "title":title}

df = pd.DataFrame(df)

In [20]:
df.dropna(axis=1,inplace= True)
df.drop_duplicates(inplace= True)

In [29]:
df.to_csv("data/dataset.csv",index = False)

In [22]:
from sklearn.preprocessing import OrdinalEncoder , LabelEncoder
import numpy as np

In [23]:
title_counts = df['title'].value_counts()
valid_titles = title_counts[title_counts >= 5].index
df_filtered = df[df['title'].isin(valid_titles)].copy()

In [26]:
df_filtered

,skills,title
0,"Python, SQL, TensorFlow, Machine Learning, Com...",Data Scientist
1,"HTML, CSS, JavaScript, React, Teamwork",Frontend Developer
2,"Java, Spring, SQL, REST APIs, Problem Solving",Backend Developer
3,"Figma, Adobe XD, UI/UX Design, Creativity",Designer
4,"Python, Django, JavaScript, React, Agile",Full Stack Python Developer
...,...,...
2156,"B2B Sales, Lead Generation, Consultative Selli...",Business Development Manager
2158,"CRM Tools, Salesforce.com, Collaboration, Comm...",Business Development Representative
2159,"Technical Sales, Sales Process Management, Cus...",Business Development Manager
2161,"sales, lead generation, customer relationship ...",Business Development Representative
2163,"Collaboration, Communication, Problem Solving,...",Business Development Representative

In [27]:
df_filtered.to_csv("data/dataset.csv",index=False)

In [18]:
ordinal = OrdinalEncoder()
label = LabelEncoder()
ordinal_title = ordinal.fit_transform(np.array(df_filtered["title"]).reshape(-1,1))
lable_title = label.fit_transform(df_filtered["title"])

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
tfidf = TfidfVectorizer(tokenizer= lambda x :[i.strip().lower() for i in x.split(',')],token_pattern= None)
tfidf_skills = tfidf.fit_transform(df_filtered["skills"])

In [21]:
tfidf_skills = tfidf_skills.toarray()

In [22]:
tfidf_skills

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(461, 2047))

In [23]:
from sklearn.decomposition import TruncatedSVD
components = [50,100,200,300,400]
truncated_data = []
for i in components:
    svd = TruncatedSVD(n_components=i,random_state = 42)
    skills_reduce = svd.fit_transform(tfidf_skills)
    truncated_data.append(skills_reduce)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

In [25]:
model_for_normal = XGBClassifier(
    n_jobs=-1,
    eval_metric='mlogloss',
    tree_method='hist',
    device='cuda'
)
model_for_svd0 =  XGBClassifier(

    n_jobs=-1,
    eval_metric='mlogloss',
    tree_method='hist',
    device='cuda'
)

model_for_svd1 =  XGBClassifier(

    n_jobs=-1,
    eval_metric='mlogloss',
    tree_method='hist',
    device='cuda'
)

model_for_svd2 =  XGBClassifier(

    n_jobs=-1,
    eval_metric='mlogloss',
    tree_method='hist',
    device='cuda'
)

model_for_svd3 =  XGBClassifier(

    n_jobs=-1,
    eval_metric='mlogloss',
    tree_method='hist',
    device='cuda'
)

model_for_svd4 =  XGBClassifier(

    n_jobs=-1,
    eval_metric='mlogloss',
    tree_method='hist',
    device='cuda'
)

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(tfidf_skills,ordinal_title,test_size=0.3)
x_train_svd0,x_test_svd0,y_train_svd0,y_test_svd0 = train_test_split(truncated_data[0],ordinal_title,test_size=0.3)
x_train_svd1,x_test_svd1,y_train_svd1,y_test_svd1 = train_test_split(truncated_data[1],ordinal_title,test_size=0.3)
x_train_svd2,x_test_svd2,y_train_svd2,y_test_svd2 = train_test_split(truncated_data[2],ordinal_title,test_size=0.3)
x_train_svd3,x_test_svd3,y_train_svd3,y_test_svd3 = train_test_split(truncated_data[3],ordinal_title,test_size=0.3)
x_train_svd4,x_test_svd4,y_train_svd4,y_test_svd4 = train_test_split(truncated_data[4],ordinal_title,test_size=0.3)

In [27]:
model_for_normal.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cuda', early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, ...)

In [30]:
model_for_svd0.fit(x_train_svd0,y_train_svd0)
model_for_svd1.fit(x_train_svd1,y_train_svd0)
model_for_svd2.fit(x_train_svd2,y_train_svd2)
model_for_svd3.fit(x_train_svd3,y_train_svd2)
model_for_svd4.fit(x_train_svd4,y_train_svd4)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cuda', early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, ...)

In [31]:
svd_predict0 = model_for_svd0.predict(x_test_svd0)
svd_predict1 = model_for_svd1.predict(x_test_svd1)
svd_predict2 = model_for_svd2.predict(x_test_svd2)
svd_predict3 = model_for_svd3.predict(x_test_svd3)
svd_predict4 = model_for_svd4.predict(x_test_svd4)

predict = model_for_normal.predict(x_test)

c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\xgboost\core.py:751: UserWarning: [15:03:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

In [32]:
from sklearn.model_selection import cross_val_score

In [34]:
print(cross_val_score(model_for_svd0,x_train_svd0,y_train_svd0,scoring="accuracy",n_jobs=-1))
print(cross_val_score(model_for_svd1,x_train_svd1,y_train_svd0,scoring="accuracy",n_jobs=-1))
print(cross_val_score(model_for_svd2,x_train_svd2,y_train_svd2,scoring="accuracy",n_jobs=-1))
print(cross_val_score(model_for_svd3,x_train_svd3,y_train_svd3,scoring="accuracy",n_jobs=-1))
print(cross_val_score(model_for_svd4,x_train_svd4,y_train_svd4,scoring="accuracy",n_jobs=-1))

c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
1 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\xgboost\core.py", line 751, in inner_f
    return func(**kwargs)
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\xgboost\sklearn.py", line 1761, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46], got [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47.]

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

[0.55384615        nan 0.453125   0.453125   0.3125    ]

c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
1 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\xgboost\core.py", line 751, in inner_f
    return func(**kwargs)
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\xgboost\sklearn.py", line 1761, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46], got [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47.]

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_split.py:811: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

[0.04615385        nan 0.09375    0.03125    0.078125  ]
[0.52307692 0.38461538 0.484375   0.46875    0.5       ]

c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_split.py:811: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

[0.46153846 0.47692308 0.484375   0.453125   0.390625  ]

c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

[0.43076923        nan        nan 0.359375   0.421875  ]

c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
2 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\xgboost\core.py", line 751, in inner_f
    return func(**kwargs)
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\xgboost\sklearn.py", line 1761, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46], got [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47.]

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\xgboost\core.py", line 751, in inner_f
    return func(**kwargs)
  File "c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\xgboost\sklearn.py", line 1761, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46], got [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47.]

  warnings.warn(some_fits_failed_message, FitFailedWarning)

In [35]:
print(cross_val_score(model_for_normal,x_train,y_train,scoring="accuracy",n_jobs=-1))

c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\sklearn\model_selection\_split.py:811: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

[0.23076923 0.26153846 0.3125     0.28125    0.296875  ]

In [18]:
from sentence_transformers import SentenceTransformer,util
from sklearn.metrics.pairwise import cosine_similarity

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]

In [19]:
transformer = SentenceTransformer("all-MiniLM-L6-v2")

c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
c:\Users\Arun\OneDrive\Documents\resume\venv\lib\site-packages\huggingface_hub\file_download.py:157: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Arun\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [21]:
df_filtered = df_filtered.reset_index(drop=True)

In [22]:
skills_embedding = transformer.encode(df_filtered["skills"])
label_embedding = transformer.encode(df_filtered["title"])

In [26]:
sentence_cosine_similarity = util.cos_sim(skills_embedding,label_embedding)

In [25]:
sklearn_cosine = cosine_similarity(skills_embedding,label_embedding)

In [31]:
import numpy as np
print(np.allclose(sentence_cosine_similarity, sklearn_cosine, atol=1e-5))
print("Max difference:", np.abs(sentence_cosine_similarity - sklearn_cosine).max())

True
Max difference: tensor(3.2783e-07)

C:\Users\Arun\AppData\Local\Temp\ipykernel_5248\1329204057.py:3: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print("Max difference:", np.abs(sentence_cosine_similarity - sklearn_cosine).max())

array([[0.44397962, 0.22505084, 0.28073364, ..., 0.20845489, 0.16887063,
        0.16887063],
       [0.18876378, 0.41716403, 0.39308637, ..., 0.1208924 , 0.18092975,
        0.18092975],
       [0.1734074 , 0.2037469 , 0.22640182, ..., 0.10281326, 0.11652592,
        0.11652592],
       ...,
       [0.27686578, 0.12459874, 0.17985195, ..., 0.35775876, 0.32382333,
        0.32382333],
       [0.32143873, 0.20997451, 0.23182386, ..., 0.43525928, 0.42870557,
        0.42870557],
       [0.34293282, 0.2076381 , 0.23208207, ..., 0.216041  , 0.24191403,
        0.24191403]], shape=(461, 461), dtype=float32)

In [30]:
import pandas as pd
df = pd.read_csv("data\dataset.csv")

In [31]:
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1265 entries, 0 to 1264
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   skills  1265 non-null   object
 1   title   1265 non-null   object
dtypes: object(2)
memory usage: 19.9+ KB

In [32]:
df.shape

(1265, 2)

In [41]:
columns = ['skills', 'title']
assert (columns == df.columns).all()